/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "btn",
    "btn-primary",
    "btn-outline",
    "btn-ghost",
    "btn-sm",
    "select",
    "select-bordered",
    "input",
    "input-bordered",
    "textarea",
    "textarea-bordered",
    "file-input",
    "file-input-bordered",
    "dropdown",
    "dropdown-bottom",
    "dropdown-end",
    "dropdown-content",
    "menu",
    "menu-sm",
    "card",
    "card-body",
    "badge",
    "badge-outline",
    "rounded-box",
    "border",
    "border-base-300",
    "bg-base-100",
    "text-base-content",
    "shadow-xl",
    "w-full",
    "flex-1",
    "rounded-xl",
    "rounded-2xl",
    "justify-between",
    "normal-case",
    "z-[30]",
    "hidden",
    "p-2",
    "p-4",
    "mt-2",
    "mt-3",
    "gap-1",
    "gap-2",
    "gap-3",
    "flex",
    "flex-wrap",
    "items-center",
    "justify-between",
    "text-sm",
    "text-xs",
    "font-semibold",
  ],
  theme: {
    extend: {},
  },
  daisyui: {
    themes: [
      {
        "supervisor-light": {
          primary: "#2f6fed",
          "primary-content": "#ffffff",
          secondary: "#5ea2ff",
          accent: "#21c46b",
          neutral: "#0f172a",
          "base-100": "#ffffff",
          "base-200": "#f4f7fb",
          "base-300": "#e3eaf4",
          info: "#2f6fed",
          success: "#21c46b",
          warning: "#f59e0b",
          error: "#fb5a52",
        },
      },
      {
        "supervisor-dark": {
          primary: "#5ea2ff",
          "primary-content": "#ffffff",
          secondary: "#79b4ff",
          accent: "#35d982",
          neutral: "#f8fbff",
          "base-100": "#121d31",
          "base-200": "#17233b",
          "base-300": "#20304c",
          info: "#5ea2ff",
          success: "#35d982",
          warning: "#ffcf7a",
          error: "#fb5a52",
        },
      },
    ],
  },
  plugins: [require("daisyui")],
};
